// Concrete viem-backed implementation of IElectionContractClient.
//
// Per the Phase 3 design decision: every method here wraps its viem call
// in a try/catch that routes failures through normalizeError() (errors.ts)
// before re-throwing. This is the actual fulfillment of ADR-004's stated
// purpose for this module ("normalizes Viem/RPC errors into a consistent
// internal error type") - centralizing it in this class's methods means
// every caller (domain modules, the worker) gets the same
// BlockchainError shape regardless of which method they called, rather
// than each call site needing to remember to wrap its own try/catch.
//
// IMPLEMENTATION NOTE on viem usage: this uses viem's readContract/
// writeContract actions directly rather than getContract({ abi, ... }).
// getContract's read.X/write.X convenience methods rely on TypeScript
// inferring literal string types from the ABI at compile time (the
// standard pattern is `const abi = [...] as const`), which only works for
// ABIs defined as in-code literals. This project's ABI is loaded from a
// JSON file generated by Phase 2's extract-abi.ts script - a deliberate
// choice (see that script's header comment) that keeps the backend
// decoupled from the contracts package's build toolchain. The trade-off is
// that the ABI's type is `Abi` (the general interface), not a literal
// type, so getContract's read/write proxies can't resolve method names
// statically and degrade to `unknown`/possibly-undefined - a real, known
// limitation, not a workaround for a mistake. readContract/writeContract
// take the function name as a plain string argument instead of a proxy
// property access, so they don't hit this limitation: they accept a
// runtime ABI value and return a precisely-typed result for any call,
// with TypeScript checking the function name and args against whatever
// the ABI's inferred type allows.

import { readContract, writeContract, waitForTransactionReceipt } from "viem/actions";
import type { Abi, PublicClient } from "viem";
import electionAbiJson from "../../../../../shared/abi/Election.json" with { type: "json" };
import { env } from "../../../config/env.js";
import { logger } from "../../../shared/logger.js";
import { normalizeError } from "../errors.js";
import { getPublicClient } from "../provider.js";
import { requireBackendWalletClient } from "../signer.js";
import type {
  CandidateData,
  ElectionData,
  IElectionContractClient,
  TransactionResult,
} from "./IElectionContractClient.js";

const blockchainLogger = logger.child({ module: "blockchain", contract: "Election" });

const electionAbi = electionAbiJson as Abi;

export class ElectionContractClient implements IElectionContractClient {
  constructor(
    private readonly address: `0x${string}` = env.CONTRACT_ADDRESS_ELECTION as `0x${string}`,
    private readonly publicClient: PublicClient = getPublicClient(),
  ) {}

  async getElection(electionId: bigint): Promise<ElectionData> {
    try {
      const result = await readContract(this.publicClient, {
        address: this.address,
        abi: electionAbi,
        functionName: "getElection",
        args: [electionId],
      });
      // viem decodes a Solidity function with exactly one output of named-
      // tuple/struct type as a plain JS object keyed by the struct's field
      // names (confirmed empirically against this exact ABI shape - see
      // HANDOFF.md's Phase 3 section) - NOT as an array-like positional
      // tuple. Destructuring by array position here previously threw
      // "TypeError: result is not iterable" against a real contract call;
      // caught by the Phase 3 integration test, not by type-checking
      // (the `as [...]` cast made TypeScript accept the wrong shape).
      const { title, startTime, endTime, finalized, creator, candidateCount } = result as {
        title: string;
        startTime: bigint;
        endTime: bigint;
        finalized: boolean;
        creator: `0x${string}`;
        candidateCount: bigint;
      };
      return { title, startTime, endTime, finalized, creator, candidateCount };
    } catch (error) {
      this.handleError(error, "getElection", { electionId });
    }
  }

  async getCandidate(electionId: bigint, candidateId: bigint): Promise<CandidateData> {
    try {
      const result = await readContract(this.publicClient, {
        address: this.address,
        abi: electionAbi,
        functionName: "getCandidate",
        args: [electionId, candidateId],
      });
      // Same viem decoding behavior as getElection above - a single
      // named-struct output decodes to a plain object, not a positional
      // tuple.
      const { name, metadataURI, voteCount } = result as { name: string; metadataURI: string; voteCount: bigint };
      return { name, metadataURI, voteCount };
    } catch (error) {
      this.handleError(error, "getCandidate", { electionId, candidateId });
    }
  }

  async hasVoted(electionId: bigint, voter: `0x${string}`): Promise<boolean> {
    try {
      const result = await readContract(this.publicClient, {
        address: this.address,
        abi: electionAbi,
        functionName: "hasVoted",
        args: [electionId, voter],
      });
      return result as boolean;
    } catch (error) {
      this.handleError(error, "hasVoted", { electionId, voter });
    }
  }

  async electionCount(): Promise<bigint> {
    try {
      const result = await readContract(this.publicClient, {
        address: this.address,
        abi: electionAbi,
        functionName: "electionCount",
        args: [],
      });
      return result as bigint;
    } catch (error) {
      this.handleError(error, "electionCount", {});
    }
  }

  async isPaused(): Promise<boolean> {
    try {
      const result = await readContract(this.publicClient, {
        address: this.address,
        abi: electionAbi,
        functionName: "paused",
        args: [],
      });
      return result as boolean;
    } catch (error) {
      this.handleError(error, "isPaused", {});
    }
  }

  async finalizeElection(electionId: bigint): Promise<TransactionResult> {
    try {
      const walletClient = requireBackendWalletClient();
      const hash = await writeContract(walletClient, {
        address: this.address,
        abi: electionAbi,
        functionName: "finalizeElection",
        args: [electionId],
        chain: walletClient.chain,
        account: walletClient.account!,
      });
      const receipt = await waitForTransactionReceipt(this.publicClient, { hash });
      return { transactionHash: hash, blockNumber: receipt.blockNumber };
    } catch (error) {
      this.handleError(error, "finalizeElection", { electionId });
    }
  }

  private handleError(error: unknown, method: string, context: Record<string, unknown>): never {
    const normalized = normalizeError(error);
    blockchainLogger.error(
      { method, context, kind: normalized.kind, retryable: normalized.retryable },
      normalized.message,
    );
    throw normalized;
  }
}